name: Python Tests (Scheduled Every 4 Hours)

on:
  schedule:
    # Chạy mỗi 4 giờ một lần (UTC)
    - cron: '0 2  * * *'
  workflow_dispatch: # Cho phép chạy thủ công khi cần

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tạo file .env từ secrets
      run: |
        echo "CLIENT_ID=${CLIENT_ID}" > .env
        echo "CLIENT_SECRET=${CLIENT_SECRET}" >> .env
        echo "TENANT_ID=${TENANT_ID}" >> .env
        echo "USER_EMAIL=${USER_EMAIL}" >> .env
        echo "EMAIL_RECIPIENTS=${EMAIL_RECIPIENTS}" >> .env
        echo "RCLONE_REMOTE=${RCLONE_REMOTE}" >> .env
        echo "RCLONE_FOLDER=${RCLONE_FOLDER}" >> .env
        echo "REMOTE_GIT=${REMOTE_GIT}" >> .env
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        RCLONE_REMOTE: ${{ secrets.RCLONE_REMOTE }}
        RCLONE_FOLDER: ${{ secrets.RCLONE_FOLDER }}
        REMOTE_GIT: 1
    - name: Run PingE5_App.py
      run: python PingE5_App.py
    #- name: run GUI.py
    #  run: timeout 300 python "PingE5_User face.py"

